Running [/home/runner/golangci-lint-2.5.0-linux-amd64/golangci-lint config path] in [/home/runner/work/kafko/kafko] ...   Running [/home/runner/golangci-lint-2.5.0-linux-amd64/golangci-lint config verify] in [/home/runner/work/kafko/kafko] ...   Running [/home/runner/golangci-lint-2.5.0-linux-amd64/golangci-lint run  --timeout=5m] in [/home/runner/work/kafko/kafko] ...   panic: file requires newer Go version go1.26 (application built with go1.25) [recovered, repanicked]
  goroutine 1914 [running]:
  go/types.(*Checker).handleBailout(0xc00a81e3c0, 0xc002ca7a18)
  	go/types/check.go:467 +0x97
  panic({0x1415540?, 0xc015a89780?})
  	runtime/panic.go:783 +0x132
  github.com/golangci/golangci-lint/v2/pkg/goanalysis.(*loadingPackage).convertError(0xc00198efc0, {0x1bb76c0?, 0xc009217ec0})
  	github.com/golangci/golangci-lint/v2/pkg/goanalysis/runner_loadingpackage.go:484 +0x714
  github.com/golangci/golangci-lint/v2/pkg/goanalysis.(*loadingPackage).loadFromSource.func2({0x1bb76c0?, 0xc009217ec0?})
  	github.com/golangci/golangci-lint/v2/pkg/goanalysis/runner_loadingpackage.go:208 +0x37
  go/types.(*Checker).handleError(0xc00a81e3c0, 0x0, {0x1bb85c0, 0xc003cec360}, 0x97, {0xc0147a47d0, 0x45}, 0x0)
  	go/types/errors.go:221 +0x44a
  go/types.(*error_).report(0xc002ca77b8)
  	go/types/errors.go:148 +0x2cc
  go/types.(*Checker).errorf(0xc0003daa10?, {0x1bb85c0, 0xc003cec360}, 0x6?, {0x1786dc0?, 0xc002ca7850?}, {0xc002ca78c0?, 0x36?, 0x37?})
  	go/types/errors.go:243 +0x150
  go/types.(*Checker).initFiles(0xc00a81e3c0, {0xc002eec3f0, 0x5, 0xc002ca7978?})
  	go/types/check.go:415 +0x771
  go/types.(*Checker).checkFiles(0xc00a81e3c0, {0xc002eec3f0?, 0x6f7145?, 0x1572b20?})
  	go/types/check.go:516 +0x18d
  go/types.(*Checker).Files(0x14c6f20?, {0xc002eec3f0?, 0xc00c66d800?, 0x5?})
  	go/types/check.go:485 +0x75
  github.com/golangci/golangci-lint/v2/pkg/goanalysis.(*loadingPackage).loadFromSource(0xc00198efc0, 0x2)
  	github.com/golangci/golangci-lint/v2/pkg/goanalysis/runner_loadingpackage.go:214 +0x73a
  github.com/golangci/golangci-lint/v2/pkg/goanalysis.(*loadingPackage).loadImportedPackageWithFacts(0xc00198efc0, 0x2)
  	github.com/golangci/golangci-lint/v2/pkg/goanalysis/runner_loadingpackage.go:378 +0x396
  github.com/golangci/golangci-lint/v2/pkg/goanalysis.(*loadingPackage).loadWithFacts(0xc002c9b510?, 0x45dcc9?)
  	github.com/golangci/golangci-lint/v2/pkg/goanalysis/runner_loadingpackage.go:321 +0x128
  github.com/golangci/golangci-lint/v2/pkg/goanalysis.(*loadingPackage).analyze(0xc00198efc0, {0x1bc7208, 0xc002651680}, 0xc0026e50c0, 0x2, 0xc0026b4770)
  	github.com/golangci/golangci-lint/v2/pkg/goanalysis/runner_loadingpackage.go:80 +0x115
  github.com/golangci/golangci-lint/v2/pkg/goanalysis.(*loadingPackage).analyzeRecursive.func1()
  	github.com/golangci/golangci-lint/v2/pkg/goanalysis/runner_loadingpackage.go:61 +0x20e
  sync.(*Once).doSlow(0x0?, 0x0?)
  	sync/once.go:78 +0xac
  sync.(*Once).Do(...)
  	sync/once.go:69
  github.com/golangci/golangci-lint/v2/pkg/goanalysis.(*loadingPackage).analyzeRecursive(0x0?, {0x1bc7208?, 0xc002651680?}, 0x0?, 0x0?, 0x0?)
  	github.com/golangci/golangci-lint/v2/pkg/goanalysis/runner_loadingpackage.go:45 +0x59
  github.com/golangci/golangci-lint/v2/pkg/goanalysis.(*loadingPackage).analyzeRecursive.func1.1(0x0?)
  	github.com/golangci/golangci-lint/v2/pkg/goanalysis/runner_loadingpackage.go:53 +0x30
  created by github.com/golangci/golangci-lint/v2/pkg/goanalysis.(*loadingPackage).analyzeRecursive.func1 in goroutine 566
  	github.com/golangci/golangci-lint/v2/pkg/goanalysis/runner_loadingpackage.go:52 +0xd4

  Error: golangci-lint exit with code 2